/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author JOSE NAVAS
 */
public class JFrame_Main extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Main
     */
    public JFrame_Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlVentanilla1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNumAsientoV1 = new javax.swing.JTextField();
        txtCambioAsientoV1 = new javax.swing.JTextField();
        txtNombrePasajeroV1 = new javax.swing.JTextField();
        btnReservarV1 = new javax.swing.JButton();
        btnCambiarV1 = new javax.swing.JButton();
        btnEliminarV1 = new javax.swing.JButton();
        pnlVentanilla2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNumAsientoV2 = new javax.swing.JTextField();
        txtCambioAsientoV2 = new javax.swing.JTextField();
        txtNombrePasajeroV2 = new javax.swing.JTextField();
        btnReservarV2 = new javax.swing.JButton();
        btnCambiarV2 = new javax.swing.JButton();
        btnEliminarV2 = new javax.swing.JButton();
        pnlVentanilla3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtNumAsientoV3 = new javax.swing.JTextField();
        txtCambioAsientoV3 = new javax.swing.JTextField();
        txtNombrePasajeroV3 = new javax.swing.JTextField();
        btnReservarV3 = new javax.swing.JButton();
        btnCambiarV3 = new javax.swing.JButton();
        btnEliminarV3 = new javax.swing.JButton();
        pnlAsientoBoleteria = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        pnlEstadoReserva = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        pnlReservaParalela = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtNumAsiento = new javax.swing.JTextField();
        btnReservarRP = new javax.swing.JButton();
        pnlVistaCola = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        btnLimpiarReservas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(100, 100));
        setMinimumSize(new java.awt.Dimension(100, 100));
        setPreferredSize(new java.awt.Dimension(100, 100));
        setSize(new java.awt.Dimension(800, 800));

        pnlMenu.setBackground(new java.awt.Color(32, 44, 49));
        pnlMenu.setMaximumSize(new java.awt.Dimension(200, 200));

        jPanel1.setBackground(new java.awt.Color(38, 167, 155));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ventanillas");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/boleto24_24.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/avion.png"))); // NOI18N
        jLabel3.setText("UG AIRLINES");

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlVentanilla1.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        jLabel4.setText("Ventanilla 1");

        jLabel5.setText("Numero de Asiento:");

        jLabel6.setText("Cambio Asiento:");

        jLabel7.setText("Nombre del Pasajero:");

        txtNumAsientoV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumAsientoV1ActionPerformed(evt);
            }
        });

        txtCambioAsientoV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCambioAsientoV1ActionPerformed(evt);
            }
        });

        txtNombrePasajeroV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePasajeroV1ActionPerformed(evt);
            }
        });

        btnReservarV1.setText("Reservar");

        btnCambiarV1.setText("Cambiar");

        btnEliminarV1.setText("Reservar");
        btnEliminarV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarV1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlVentanilla1Layout = new javax.swing.GroupLayout(pnlVentanilla1);
        pnlVentanilla1.setLayout(pnlVentanilla1Layout);
        pnlVentanilla1Layout.setHorizontalGroup(
            pnlVentanilla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVentanilla1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlVentanilla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVentanilla1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumAsientoV1))
                    .addGroup(pnlVentanilla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4)
                        .addGroup(pnlVentanilla1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNombrePasajeroV1))
                        .addGroup(pnlVentanilla1Layout.createSequentialGroup()
                            .addComponent(btnReservarV1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnCambiarV1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnEliminarV1))
                        .addGroup(pnlVentanilla1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCambioAsientoV1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlVentanilla1Layout.setVerticalGroup(
            pnlVentanilla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVentanilla1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(pnlVentanilla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNumAsientoV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlVentanilla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCambioAsientoV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlVentanilla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNombrePasajeroV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlVentanilla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReservarV1)
                    .addComponent(btnCambiarV1)
                    .addComponent(btnEliminarV1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlVentanilla2.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        jLabel8.setText("Ventanilla 2");

        jLabel9.setText("Numero de Asiento:");

        jLabel10.setText("Cambio Asiento:");

        jLabel11.setText("Nombre del Pasajero:");

        txtNumAsientoV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumAsientoV2ActionPerformed(evt);
            }
        });

        txtCambioAsientoV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCambioAsientoV2ActionPerformed(evt);
            }
        });

        txtNombrePasajeroV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePasajeroV2ActionPerformed(evt);
            }
        });

        btnReservarV2.setText("Reservar");

        btnCambiarV2.setText("Cambiar");

        btnEliminarV2.setText("Reservar");
        btnEliminarV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarV2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlVentanilla2Layout = new javax.swing.GroupLayout(pnlVentanilla2);
        pnlVentanilla2.setLayout(pnlVentanilla2Layout);
        pnlVentanilla2Layout.setHorizontalGroup(
            pnlVentanilla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVentanilla2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlVentanilla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addGroup(pnlVentanilla2Layout.createSequentialGroup()
                        .addComponent(btnReservarV2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCambiarV2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarV2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVentanilla2Layout.createSequentialGroup()
                        .addGroup(pnlVentanilla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlVentanilla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNumAsientoV2, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(txtNombrePasajeroV2)
                            .addComponent(txtCambioAsientoV2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlVentanilla2Layout.setVerticalGroup(
            pnlVentanilla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVentanilla2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(pnlVentanilla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNumAsientoV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlVentanilla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCambioAsientoV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlVentanilla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtNombrePasajeroV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlVentanilla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReservarV2)
                    .addComponent(btnCambiarV2)
                    .addComponent(btnEliminarV2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlVentanilla3.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        jLabel12.setText("Ventanilla 3");

        jLabel13.setText("Numero de Asiento:");

        jLabel14.setText("Cambio Asiento:");

        jLabel15.setText("Nombre del Pasajero:");

        txtNumAsientoV3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumAsientoV3ActionPerformed(evt);
            }
        });

        txtCambioAsientoV3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCambioAsientoV3ActionPerformed(evt);
            }
        });

        txtNombrePasajeroV3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePasajeroV3ActionPerformed(evt);
            }
        });

        btnReservarV3.setText("Reservar");

        btnCambiarV3.setText("Cambiar");

        btnEliminarV3.setText("Reservar");
        btnEliminarV3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarV3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlVentanilla3Layout = new javax.swing.GroupLayout(pnlVentanilla3);
        pnlVentanilla3.setLayout(pnlVentanilla3Layout);
        pnlVentanilla3Layout.setHorizontalGroup(
            pnlVentanilla3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVentanilla3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlVentanilla3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVentanilla3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumAsientoV3))
                    .addGroup(pnlVentanilla3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel12)
                        .addGroup(pnlVentanilla3Layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNombrePasajeroV3))
                        .addGroup(pnlVentanilla3Layout.createSequentialGroup()
                            .addComponent(btnReservarV3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnCambiarV3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnEliminarV3))
                        .addGroup(pnlVentanilla3Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCambioAsientoV3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlVentanilla3Layout.setVerticalGroup(
            pnlVentanilla3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVentanilla3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(pnlVentanilla3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtNumAsientoV3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlVentanilla3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtCambioAsientoV3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlVentanilla3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtNombrePasajeroV3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlVentanilla3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReservarV3)
                    .addComponent(btnCambiarV3)
                    .addComponent(btnEliminarV3))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pnlAsientoBoleteria.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        jLabel16.setText("Asiento Boleteria");

        javax.swing.GroupLayout pnlAsientoBoleteriaLayout = new javax.swing.GroupLayout(pnlAsientoBoleteria);
        pnlAsientoBoleteria.setLayout(pnlAsientoBoleteriaLayout);
        pnlAsientoBoleteriaLayout.setHorizontalGroup(
            pnlAsientoBoleteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAsientoBoleteriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAsientoBoleteriaLayout.setVerticalGroup(
            pnlAsientoBoleteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAsientoBoleteriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pnlEstadoReserva.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        jLabel17.setText("Estado de Reserva");

        javax.swing.GroupLayout pnlEstadoReservaLayout = new javax.swing.GroupLayout(pnlEstadoReserva);
        pnlEstadoReserva.setLayout(pnlEstadoReservaLayout);
        pnlEstadoReservaLayout.setHorizontalGroup(
            pnlEstadoReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEstadoReservaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlEstadoReservaLayout.setVerticalGroup(
            pnlEstadoReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEstadoReservaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pnlReservaParalela.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        jLabel18.setText("Reserva Paralela");

        jLabel20.setText("Numero de Asiento:");

        btnReservarRP.setText("Reservar");

        javax.swing.GroupLayout pnlReservaParalelaLayout = new javax.swing.GroupLayout(pnlReservaParalela);
        pnlReservaParalela.setLayout(pnlReservaParalelaLayout);
        pnlReservaParalelaLayout.setHorizontalGroup(
            pnlReservaParalelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReservaParalelaLayout.createSequentialGroup()
                .addGroup(pnlReservaParalelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlReservaParalelaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlReservaParalelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(pnlReservaParalelaLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlReservaParalelaLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnReservarRP)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        pnlReservaParalelaLayout.setVerticalGroup(
            pnlReservaParalelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReservaParalelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(pnlReservaParalelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtNumAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnReservarRP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlVistaCola.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        jLabel19.setText("Vista de Cola");

        javax.swing.GroupLayout pnlVistaColaLayout = new javax.swing.GroupLayout(pnlVistaCola);
        pnlVistaCola.setLayout(pnlVistaColaLayout);
        pnlVistaColaLayout.setHorizontalGroup(
            pnlVistaColaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVistaColaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlVistaColaLayout.setVerticalGroup(
            pnlVistaColaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVistaColaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        btnLimpiarReservas.setText("Limpiar Reservas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(pnlVentanilla1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pnlVentanilla2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pnlVentanilla3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(pnlReservaParalela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnlAsientoBoleteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(24, 24, 24)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pnlEstadoReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnlVistaCola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(btnLimpiarReservas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlVentanilla3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlVentanilla1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlVentanilla2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAsientoBoleteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlEstadoReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlVistaCola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlReservaParalela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(btnLimpiarReservas)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombrePasajeroV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePasajeroV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePasajeroV1ActionPerformed

    private void txtCambioAsientoV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCambioAsientoV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCambioAsientoV1ActionPerformed

    private void txtNumAsientoV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumAsientoV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumAsientoV1ActionPerformed

    private void btnEliminarV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarV1ActionPerformed

    private void txtNumAsientoV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumAsientoV2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumAsientoV2ActionPerformed

    private void txtCambioAsientoV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCambioAsientoV2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCambioAsientoV2ActionPerformed

    private void txtNombrePasajeroV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePasajeroV2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePasajeroV2ActionPerformed

    private void btnEliminarV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarV2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarV2ActionPerformed

    private void txtNumAsientoV3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumAsientoV3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumAsientoV3ActionPerformed

    private void txtCambioAsientoV3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCambioAsientoV3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCambioAsientoV3ActionPerformed

    private void txtNombrePasajeroV3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePasajeroV3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePasajeroV3ActionPerformed

    private void btnEliminarV3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarV3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarV3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarV1;
    private javax.swing.JButton btnCambiarV2;
    private javax.swing.JButton btnCambiarV3;
    private javax.swing.JButton btnEliminarV1;
    private javax.swing.JButton btnEliminarV2;
    private javax.swing.JButton btnEliminarV3;
    private javax.swing.JButton btnLimpiarReservas;
    private javax.swing.JButton btnReservarRP;
    private javax.swing.JButton btnReservarV1;
    private javax.swing.JButton btnReservarV2;
    private javax.swing.JButton btnReservarV3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlAsientoBoleteria;
    private javax.swing.JPanel pnlEstadoReserva;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlReservaParalela;
    private javax.swing.JPanel pnlVentanilla1;
    private javax.swing.JPanel pnlVentanilla2;
    private javax.swing.JPanel pnlVentanilla3;
    private javax.swing.JPanel pnlVistaCola;
    private javax.swing.JTextField txtCambioAsientoV1;
    private javax.swing.JTextField txtCambioAsientoV2;
    private javax.swing.JTextField txtCambioAsientoV3;
    private javax.swing.JTextField txtNombrePasajeroV1;
    private javax.swing.JTextField txtNombrePasajeroV2;
    private javax.swing.JTextField txtNombrePasajeroV3;
    private javax.swing.JTextField txtNumAsiento;
    private javax.swing.JTextField txtNumAsientoV1;
    private javax.swing.JTextField txtNumAsientoV2;
    private javax.swing.JTextField txtNumAsientoV3;
    // End of variables declaration//GEN-END:variables
}
